"""Added jobs table

Revision ID: 2c134222837c
Revises: c59dc9d6f3bd
Create Date: 2026-01-04 17:08:18.365098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c134222837c'
down_revision = 'c59dc9d6f3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('salary_range', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('application_deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('apply_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('job_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('posted_by',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('posted_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('job_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('apply_link')
        batch_op.drop_column('application_deadline')
        batch_op.drop_column('salary_range')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
