"""Added phone no and linkedin URL

Revision ID: 52071e630fec
Revises: 5b31e549452b
Create Date: 2026-01-22 23:00:38.046413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52071e630fec'
down_revision = '5b31e549452b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('linkedin_profile', sa.String(length=200), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('linkedin_profile', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('linkedin_profile')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_column('linkedin_profile')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('alumni', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
