"""Prevent duplications

Revision ID: 694022367909
Revises: 70f6f577c28f
Create Date: 2026-02-03 22:45:44.036250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694022367909'
down_revision = '70f6f577c28f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_job_student_application', ['job_id', 'student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_job_student_application', type_='unique')

    # ### end Alembic commands ###
