"""Add user role enum and role tables

Revision ID: 6d147795c6c3
Revises: 7e26b5689b11
Create Date: 2025-12-21 16:23:20.131988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d147795c6c3'
down_revision = '7e26b5689b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('batch_year', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('alumni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.drop_column('bio')
        batch_op.drop_column('linkedin_url')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_column('email_official')
        batch_op.drop_column('expertise')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('STUDENT', 'ALUMNI', 'FACULTY', 'ADMIN', 'PLACEMENT', name='userrole'),
               existing_nullable=False)
        batch_op.drop_column('department')
        batch_op.drop_column('faculty_id')
        batch_op.drop_column('skills')
        batch_op.drop_column('current_role')
        batch_op.drop_column('current_company')
        batch_op.drop_column('designation')
        batch_op.drop_column('batch_year')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('batch_year', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('designation', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_company', mysql.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('current_role', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('skills', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('faculty_id', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('department', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.Enum('STUDENT', 'ALUMNI', 'FACULTY', 'ADMIN', 'PLACEMENT', name='userrole'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expertise', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('email_official', mysql.VARCHAR(length=120), nullable=True))

    with op.batch_alter_table('alumni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', mysql.TEXT(), nullable=True))
        batch_op.drop_column('skills')

    op.drop_table('students')
    # ### end Alembic commands ###
