"""Updated jobs table

Revision ID: 70f6f577c28f
Revises: 0c84360f843a
Create Date: 2026-02-03 21:25:44.633749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70f6f577c28f'
down_revision = '0c84360f843a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_website', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('job_poster', sa.String(length=500), nullable=True))
        batch_op.drop_column('is_from_banner')
        batch_op.drop_column('banner_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_from_banner', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('job_poster')
        batch_op.drop_column('company_website')

    # ### end Alembic commands ###
