"""Added image and pdf upload option in events

Revision ID: 9211388e38d5
Revises: 3b27d93ba735
Create Date: 2026-01-18 15:17:07.065948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9211388e38d5'
down_revision = '3b27d93ba735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('pdf_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('pdf_file')
        batch_op.drop_column('banner_image')

    # ### end Alembic commands ###
