"""Added profile photo

Revision ID: 993b74c437aa
Revises: ab1aa28aa970
Create Date: 2026-01-18 13:40:46.986573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '993b74c437aa'
down_revision = 'ab1aa28aa970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=255), nullable=True))
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('STUDENT', 'ALUMNI', 'FACULTY', 'ADMIN', 'PLACEMENT'),
               type_=sa.Enum('INSTITUTE', 'STUDENT', 'ALUMNI', 'FACULTY', 'PLACEMENT', name='userrole'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('INSTITUTE', 'STUDENT', 'ALUMNI', 'FACULTY', 'PLACEMENT', name='userrole'),
               type_=mysql.ENUM('STUDENT', 'ALUMNI', 'FACULTY', 'ADMIN', 'PLACEMENT'),
               existing_nullable=False)
        batch_op.drop_column('profile_photo')

    # ### end Alembic commands ###
