"""Added job/internship banner image

Revision ID: a86c55665ab8
Revises: 993b74c437aa
Create Date: 2026-01-18 14:08:07.298020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86c55665ab8'
down_revision = '993b74c437aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_from_banner', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('is_from_banner')
        batch_op.drop_column('banner_image')

    # ### end Alembic commands ###
