"""Added reports table

Revision ID: c59dc9d6f3bd
Revises: c832b95b72b2
Create Date: 2026-01-02 22:09:24.678449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c59dc9d6f3bd'
down_revision = 'c832b95b72b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('filters', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('report_from', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('report_to', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('report_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('generated_by',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('generated_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('report_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('report_to')
        batch_op.drop_column('report_from')
        batch_op.drop_column('status')
        batch_op.drop_column('filters')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
