"""Modified Alumni Table

Revision ID: cd0af67d5f7d
Revises: 6d147795c6c3
Create Date: 2025-12-21 18:02:44.489621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd0af67d5f7d'
down_revision = '6d147795c6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_profile', sa.String(length=200), nullable=True))
        batch_op.drop_column('skills')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', mysql.TEXT(), nullable=True))
        batch_op.drop_column('linkedin_profile')

    # ### end Alembic commands ###
